### PR TITLE
Initial commit

### PR DESCRIPTION
**Pull request by acauret**
Initial commit as discussed

### CODE REVIEW

**Comment by acauret** [comment]
@microsoft-github-policy-service agree

**Comment by segraef** [comment]
Thanks, can you show us successful e2e test runs in your fork? FYI, the e2e tests triggered by this PR will fail and shouldn't bother you, we're currently transitioning to self-hosted GitHub runners to fix this issue.

**Comment by acauret** [comment]
image

**Comment by acauret** [comment]
> image

The SPN will need to be added to the Directory Readers role as the customer manged key example uses 'azuread_service_principal'

**Comment by segraef** [comment]
@matt

> > image
> 
> The SPN will need to be added to the Directory Readers role as the customer manged key example uses 'azuread_service_principal'

@matt-FFFFFF how do we 

> > image
> 
> The SPN will need to be added to the Directory Readers role as the customer manged key example uses 'azuread_service_principal'

picture doesn't show up for me

**Comment by segraef** [comment]
Also added you as collaborator so you can start using a local branch. We need to move this PR to a local branch in order to get the e2e tests green for now until we moved to self-hosted runners.

**Comment by segraef** [comment]
Just updated main with latest changes from the template.

**Comment by segraef** [comment]
Hi @acauret did you find a chance to accept your invitation?

image

**Comment by segraef** [comment]
Set up a session to sync with @acauret tonight.

**Pull request closed without merging**
