### PR TITLE
Added output databricks_access_connector_principal_ids

### PR DESCRIPTION
**Pull request by marcelobern**
## Description

Added output `databricks_access_connector_principal_ids`, so the access connector `principal_id` can be used in outside the module (e.g. `azurerm_role_assignment`). `terraform-docs` was used to updat `README.md`.

## Type of Change

- [ ] Non-module change (e.g. CI/CD, documentation, etc.)
- [ ] Azure Verified Module updates:
  - [X] Bugfix containing backwards compatible bug fixes, and I have NOT bumped the MAJOR or MINOR version in `locals.version.tf.json`:
    - [ ] Someone has opened a bug report issue, and I have included "Closes #{bug_report_issue_number}" in the PR description.
    - [ ] The bug was found by the module author, and no one has opened an issue to report it yet.
  - [ ] Feature update backwards compatible feature updates, and I have bumped the MINOR version in `locals.version.tf.json`.
  - [ ] Breaking changes and I have bumped the MAJOR version in `locals.version.tf.json`.
  - [ ] Update to documentation

# Checklist

- [X] I'm sure there are no other open Pull Requests for the same update/change
- [X] My corresponding pipelines / checks run clean and green without any errors or warnings
- [X] I did run all  [pre-commit](https://azure.github.io/Azure-Verified-Modules/contributing/terraform/terraform-contribution-flow/#5-run-pre-commit-checks) checks

### CODE REVIEW

**Comment by marcelobern** [comment]
I tried following the steps indicated but was unable to get the status check to show up in the PR: https://github.com/marcelobern/.github/pull/2

**Comment by marcelobern** [comment]
@microsoft-github-policy-service agree

**Comment by segraef** [comment]
Thanks @marcelobern, do you mind having a look at the linter errors, should be easy to fix and then I'm happy to approve.

**Comment by marcelobern** [comment]
@segraef sorry for the delayed response to this.

It should be good now.

**Comment by Dipak-Mistry-WTW** [comment]
Hi @segraef  @jaredfholgate  @prjelesi 
Is this just waiting for approval?

**Comment by prjelesi** [comment]
@segraef feel free to merge

**Comment by Dipak-Mistry-WTW** [comment]
This is good to have in the long term but I don't need it anymore as I have switched to User assigned managed identities instead which are output from another module.

**Comment by Dipak-Mistry-WTW** [comment]
Hi - Its seems we've changed direction and we do need this now!! Sorry for messing you about. I think the work is pretty much done. Is it just some quick linting fixes? @segraef @marcelobern

**Comment by segraef** [comment]
Approved e2e test run, please make sure to run `./avm pre-commit`.

**Review by segraef — APPROVED** [review]
@marcelobern have you had a chance to check the linter issues?

**Comment by marcelobern** [comment]
Bumped version.

Having issue with `./avm pre-commit` (see error messages below). Any suggestions? 

```
latest: Pulling from azterraform
Digest: sha256:8db46870078308c6d8310538903d0c8ee2d532a5ca99d6f8dfb0637fe6d51677
Status: Image is up to date for mcr.microsoft.com/azterraform:latest
curl: (6) Could not resolve host: raw.githubusercontent.com
make: *** No rule to make target 'pre-commit'.  Stop.
```

**Comment by Dipak-Mistry-WTW** [comment]
@jaredfholgate @segraef @marcelobern  Has this fallen off the radar?

**Comment by segraef** [comment]
I'm about to fix the linter issues together with @acauret while you can restart the [failed e2e](https://github.com/Azure/terraform-azurerm-avm-res-databricks-workspace/actions/runs/9394309114/job/27069788259?pr=29) test again to pick a fresh random location. We might need to fix the location since db ws is only available in. major regions.

**Comment by segraef** [comment]
Predecessor: #53

**Comment by segraef** [comment]
Merge #53, please rebase to get linters green, thank you @marcelobern and @Dipak-Mistry-WTW.

**Comment by marcelobern** [comment]
@segraef , I did merge #53 but I am still having issues trying to run `./avm pre-commit` locally:
```
latest: Pulling from azterraform
Digest: sha256:f19e62cacd83ab058742377bc4a561f9732845d9c4e07220dc89cceac5e69262
Status: Image is up to date for mcr.microsoft.com/azterraform:latest
curl: (6) Could not resolve host: raw.githubusercontent.com
make: *** No rule to make target 'pre-commit'.  Stop.
```

We will see it the check happen to work in the PR.

**Comment by marcelobern** [comment]
@segraef never mind, seems like I ran out of disk space due to the size of the images pulled by './avm pre-commit'.

I ran it successfully after cleaning up the disk and it removed the extra blank lines in the `README`, so I hope this will be all green now.

**Comment by segraef** [comment]
Thanks @marcelobern, please have a look at the linter and add `modtm` to required providers due to the new custom telemetry provider 

```
terraform {
  required_providers {
    # .. other required providers
    modtm = {
      source = azure/modtm
      version = "~> 0.3"
    }
  }
}
```

**Comment by marcelobern** [comment]
@segraef I am happy to do this as a favor but clearly this is not related to the code changes in this PR., so I suggest the team review the PR process to ensure PR contributors have to deal only with the PR changes and not technical debt that might have been introduced in the code.by others.

**Comment by marcelobern** [comment]
@segraef README updated

**Comment by segraef** [comment]
Fixed remaining linter changes via #56, please rebase (if necessary).

**Comment by segraef** [comment]
@marcelobern I reached out to @acauret, the main contributor of this module, and he's happy to support in respect to the failing e2e tests but please first rebase, thanks.

**Comment by segraef** [comment]
solved via #29

**Comment by segraef** [comment]
Hi @marcelobern, your change was incorporated, please feel free to close this PR, thank you for you contribution.

**Pull request closed without merging**
